### ISSUE TITLE
Paths not correctly inferred

### ISSUE THREAD

**Issue by manurana** [mxitgo/samwatch#3]
Here is a snippet from my template.yml (`/Users/manu/developer/kindl/kindl-backend-2/template.yaml`)

```yaml
  GiftCodeLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: appGiftCode.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 20
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /shopify/gift_code/validate
            Method: POST
            ApiId: !Ref MyHttpApi
            PayloadFormatVersion: "2.0"
```

The handler file `/Users/manu/developer/kindl/kindl-backend-2/src/appGiftCode.js` further refers to files in a subfolder (done to allow codes for multiple lambdas to co-exist)
```javascript
const InputUtils = require("./appGiftCodeSrc/inputUtils");
```

When I change this file, samwatch gives me the following error 
```
Error found in script execution, running fallback action, error:  File: /Users/manu/developer/kindl/kindl-backend-2/.aws-sam/build/src/appGiftCodeSrc/inputUtils.js does not exist in sam-build directory
```

The correct location for this file inside the sam build folder is `/Users/manu/developer/kindl/kindl-backend-2/.aws-sam/build/GiftCodeLambda/appGiftCodeSrc/inputUtils.js`
